apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: resume-analyzer
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  tls:
    - hosts:
        - resume-analyzer.example.com
      secretName: resume-analyzer-prod-tls
  rules:
    - host: resume-analyzer.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: resume-analyzer
                port:
                  number: 80
