apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: resume-analyzer
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - host: resume-analyzer.localtest.me
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: resume-analyzer
                port:
                  number: 80
