/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthSignupRouteImport } from './routes/auth.signup'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as ApiVersionRouteImport } from './routes/api/version'
import { Route as ApiReadyRouteImport } from './routes/api/ready'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiConfigRouteImport } from './routes/api/config'
import { Route as AuthenticatedResultsRouteImport } from './routes/_authenticated/results'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedKeywordsRouteImport } from './routes/_authenticated/keywords'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCoverLetterRouteImport } from './routes/_authenticated/cover-letter'

const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVersionRoute = ApiVersionRouteImport.update({
  id: '/api/version',
  path: '/api/version',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReadyRoute = ApiReadyRouteImport.update({
  id: '/api/ready',
  path: '/api/ready',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConfigRoute = ApiConfigRouteImport.update({
  id: '/api/config',
  path: '/api/config',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedResultsRoute = AuthenticatedResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKeywordsRoute = AuthenticatedKeywordsRouteImport.update({
  id: '/keywords',
  path: '/keywords',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCoverLetterRoute =
  AuthenticatedCoverLetterRouteImport.update({
    id: '/cover-letter',
    path: '/cover-letter',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/faq': typeof FaqRoute
  '/features': typeof FeaturesRoute
  '/pricing': typeof PricingRoute
  '/templates': typeof TemplatesRoute
  '/cover-letter': typeof AuthenticatedCoverLetterRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/keywords': typeof AuthenticatedKeywordsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/results': typeof AuthenticatedResultsRoute
  '/api/config': typeof ApiConfigRoute
  '/api/health': typeof ApiHealthRoute
  '/api/ready': typeof ApiReadyRoute
  '/api/version': typeof ApiVersionRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/faq': typeof FaqRoute
  '/features': typeof FeaturesRoute
  '/pricing': typeof PricingRoute
  '/templates': typeof TemplatesRoute
  '/cover-letter': typeof AuthenticatedCoverLetterRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/keywords': typeof AuthenticatedKeywordsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/results': typeof AuthenticatedResultsRoute
  '/api/config': typeof ApiConfigRoute
  '/api/health': typeof ApiHealthRoute
  '/api/ready': typeof ApiReadyRoute
  '/api/version': typeof ApiVersionRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/faq': typeof FaqRoute
  '/features': typeof FeaturesRoute
  '/pricing': typeof PricingRoute
  '/templates': typeof TemplatesRoute
  '/_authenticated/cover-letter': typeof AuthenticatedCoverLetterRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/keywords': typeof AuthenticatedKeywordsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/results': typeof AuthenticatedResultsRoute
  '/api/config': typeof ApiConfigRoute
  '/api/health': typeof ApiHealthRoute
  '/api/ready': typeof ApiReadyRoute
  '/api/version': typeof ApiVersionRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/faq'
    | '/features'
    | '/pricing'
    | '/templates'
    | '/cover-letter'
    | '/dashboard'
    | '/history'
    | '/keywords'
    | '/profile'
    | '/results'
    | '/api/config'
    | '/api/health'
    | '/api/ready'
    | '/api/version'
    | '/auth/login'
    | '/auth/signup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/faq'
    | '/features'
    | '/pricing'
    | '/templates'
    | '/cover-letter'
    | '/dashboard'
    | '/history'
    | '/keywords'
    | '/profile'
    | '/results'
    | '/api/config'
    | '/api/health'
    | '/api/ready'
    | '/api/version'
    | '/auth/login'
    | '/auth/signup'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/faq'
    | '/features'
    | '/pricing'
    | '/templates'
    | '/_authenticated/cover-letter'
    | '/_authenticated/dashboard'
    | '/_authenticated/history'
    | '/_authenticated/keywords'
    | '/_authenticated/profile'
    | '/_authenticated/results'
    | '/api/config'
    | '/api/health'
    | '/api/ready'
    | '/api/version'
    | '/auth/login'
    | '/auth/signup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  FaqRoute: typeof FaqRoute
  FeaturesRoute: typeof FeaturesRoute
  PricingRoute: typeof PricingRoute
  TemplatesRoute: typeof TemplatesRoute
  ApiConfigRoute: typeof ApiConfigRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiReadyRoute: typeof ApiReadyRoute
  ApiVersionRoute: typeof ApiVersionRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/version': {
      id: '/api/version'
      path: '/api/version'
      fullPath: '/api/version'
      preLoaderRoute: typeof ApiVersionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ready': {
      id: '/api/ready'
      path: '/api/ready'
      fullPath: '/api/ready'
      preLoaderRoute: typeof ApiReadyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/config': {
      id: '/api/config'
      path: '/api/config'
      fullPath: '/api/config'
      preLoaderRoute: typeof ApiConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/results': {
      id: '/_authenticated/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof AuthenticatedResultsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/keywords': {
      id: '/_authenticated/keywords'
      path: '/keywords'
      fullPath: '/keywords'
      preLoaderRoute: typeof AuthenticatedKeywordsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cover-letter': {
      id: '/_authenticated/cover-letter'
      path: '/cover-letter'
      fullPath: '/cover-letter'
      preLoaderRoute: typeof AuthenticatedCoverLetterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCoverLetterRoute: typeof AuthenticatedCoverLetterRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedKeywordsRoute: typeof AuthenticatedKeywordsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedResultsRoute: typeof AuthenticatedResultsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCoverLetterRoute: AuthenticatedCoverLetterRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedKeywordsRoute: AuthenticatedKeywordsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedResultsRoute: AuthenticatedResultsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  FaqRoute: FaqRoute,
  FeaturesRoute: FeaturesRoute,
  PricingRoute: PricingRoute,
  TemplatesRoute: TemplatesRoute,
  ApiConfigRoute: ApiConfigRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiReadyRoute: ApiReadyRoute,
  ApiVersionRoute: ApiVersionRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
