apiVersion: v1
kind: Service
metadata:
  name: resume-analyzer
  labels:
    app.kubernetes.io/name: resume-analyzer
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: resume-analyzer
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
